In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path = r"D:\airepos\forked_ai_roadmap\ai-roadmap\content\ml\supervised\02 multiple linear regression\data\housing.csv"

In [4]:
df = pd.read_csv(file_path)

In [5]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

# 1. Preprocessing #

In [6]:
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns
numerical_features

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking'], dtype='object')

In [7]:
# Identyfying binary (boolean - yes/no) columns

binary_columns = [col for col in df.columns if df[col].nunique() == 2]
binary_columns

['mainroad',
 'guestroom',
 'basement',
 'hotwaterheating',
 'airconditioning',
 'prefarea']

In [8]:
df[binary_columns] = df[binary_columns].applymap(lambda x: 1 if x == 'yes' else 0)
df.head()

C:\Users\NoteService\AppData\Local\Temp\ipykernel_13496\3716264404.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[binary_columns] = df[binary_columns].applymap(lambda x: 1 if x == 'yes' else 0)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished

In [9]:
from sklearn.preprocessing import OneHotEncoder

on_h_en = OneHotEncoder(sparse_output=False)

on_h_en.fit(df[['furnishingstatus']])

encoded_df_furnishingstatus = pd.DataFrame(data=on_h_en.transform(df[['furnishingstatus']]), columns=on_h_en.get_feature_names_out())

df = df.drop(['furnishingstatus'], axis=1)
df = pd.concat([df, encoded_df_furnishingstatus], axis=1)

In [10]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1.0,0.0,0.0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1.0,0.0,0.0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,0.0,1.0,0.0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1.0,0.0,0.0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1.0,0.0,0.0

In [11]:
df.isna().sum()

price                              0
area                               0
bedrooms                           0
bathrooms                          0
stories                            0
mainroad                           0
guestroom                          0
basement                           0
hotwaterheating                    0
airconditioning                    0
parking                            0
prefarea                           0
furnishingstatus_furnished         0
furnishingstatus_semi-furnished    0
furnishingstatus_unfurnished       0
dtype: int64

In [12]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

df[numerical_features] = min_max_scaler.fit_transform(df[numerical_features])

In [13]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,1.000000,0.396564,0.6,0.333333,0.666667,1,0,0,0,1,0.666667,1,1.0,0.0,0.0
1,0.909091,0.502405,0.6,1.000000,1.000000,1,0,0,0,1,1.000000,0,1.0,0.0,0.0
2,0.909091,0.571134,0.4,0.333333,0.333333,1,0,1,0,0,0.666667,1,0.0,1.0,0.0
3,0.906061,0.402062,0.6,0.333333,0.333333,1,0,1,0,1,1.000000,1,1.0,0.0,0.0
4,0.836364,0.396564,0.6,0.000000,0.333333,1,1,1,0,1,0.666667,0,1.0,0.0,0.0

In [14]:
# Splitting into train-test

from sklearn.model_selection import train_test_split

X = df.drop('price', axis=1)
Y = df['price']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [15]:
x_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
46,0.298969,0.4,0.333333,1.000000,1,0,0,0,1,0.333333,0,1.0,0.0,0.0
93,0.381443,0.4,0.333333,0.000000,1,0,1,0,1,1.000000,0,0.0,1.0,0.0
335,0.148866,0.2,0.000000,0.000000,1,0,1,0,1,0.666667,0,1.0,0.0,0.0
412,0.065979,0.4,0.000000,0.333333,1,0,1,0,0,0.000000,1,0.0,0.0,1.0
471,0.144330,0.4,0.000000,0.333333,1,0,0,0,0,0.000000,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,0.298969,0.6,0.333333,1.000000,1,0,0,0,1,0.000000,0,0.0,0.0,1.0
106,0.261168,0.6,0.333333,0.000000,1,0,1,0,1,0.000000,1,0.0,1.0,0.0
270,0.195876,0.4,0.333333,0.666667,1,0,0,1,0,0.333333,0,1.0,0.0,0.0
435,0.164261,0.2,0.000000,0.000000,1,0,0,0,0,0.000000,0,0.0,0.0,1.0
102,0.264605,0.4,0.333333,1.000000,1,1,0,0,1,0.333333,0,0.0,1.0,0.0

In [16]:
from sklearn.linear_model import LinearRegression

mult_lin_reg = LinearRegression()

mult_lin_reg.fit(x_train, y_train)

LinearRegression()

In [17]:
mult_lin_reg.intercept_ , mult_lin_reg.coef_

(np.float64(0.025792670235166376),
 array([ 0.2972594 ,  0.03323753,  0.28427137,  0.10583808,  0.03185454,
         0.02005282,  0.03378798,  0.05927705,  0.0685218 ,  0.0584005 ,
         0.05453598,  0.01559962,  0.00461418, -0.0202138 ]))

### Now, do without sklearn ###

In [18]:
np_x_train = x_train.to_numpy()
np_x_train.shape

(436, 14)

In [19]:
np_y_train = y_train.to_numpy()
np_y_train.shape

(436,)

In [20]:
ones = np.ones((np_x_train.shape[0], 1))  # explicitly 2D column
np_x_train_final = np.hstack((ones, np_x_train))
np_x_train_final

array([[1.        , 0.29896907, 0.4       , ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.3814433 , 0.4       , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.14886598, 0.2       , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.19587629, 0.4       , ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.16426117, 0.2       , ..., 0.        , 0.        ,
        1.        ],
       [1.        , 0.26460481, 0.4       , ..., 0.        , 1.        ,
        0.        ]])

In [21]:
beta = np.linalg.inv(np_x_train.T @ np_x_train) @ np_x_train.T @ np_y_train
beta

array([0.2972594 , 0.03323753, 0.28427137, 0.10583808, 0.03185454,
       0.02005282, 0.03378798, 0.05927705, 0.0685218 , 0.0584005 ,
       0.05453598, 0.04139229, 0.03040685, 0.00557887])

## Model Evaluation ##

In [22]:
mult_lin_reg.intercept_ , mult_lin_reg.coef_

(np.float64(0.025792670235166376),
 array([ 0.2972594 ,  0.03323753,  0.28427137,  0.10583808,  0.03185454,
         0.02005282,  0.03378798,  0.05927705,  0.0685218 ,  0.0584005 ,
         0.05453598,  0.01559962,  0.00461418, -0.0202138 ]))

In [34]:
y_test

316    0.200000
77     0.424242
360    0.169697
90     0.406061
493    0.090909
         ...
15     0.636364
357    0.175152
39     0.533333
54     0.484848
155    0.327273
Name: price, Length: 109, dtype: float64

In [36]:
mult_lin_reg.predict(x_test)

array([0.29564103, 0.47400193, 0.11773708, 0.24779873, 0.13373561,
       0.15430953, 0.33435278, 0.39983948, 0.08423004, 0.07613901,
       0.68112896, 0.09074349, 0.12303868, 0.14239299, 0.16719382,
       0.3041721 , 0.11133883, 0.26286777, 0.22506943, 0.15778027,
       0.34847404, 0.35818126, 0.08492088, 0.25777632, 0.3025842 ,
       0.50262547, 0.1273412 , 0.2979999 , 0.55356943, 0.14275447,
       0.41044961, 0.135507  , 0.42930367, 0.21227171, 0.15649966,
       0.35385061, 0.26481911, 0.22622327, 0.12478294, 0.24645497,
       0.24381323, 0.1530545 , 0.47236751, 0.19338505, 0.17310292,
       0.21859144, 0.43354477, 0.1980364 , 0.17483419, 0.14438333,
       0.47778499, 0.09112852, 0.22439399, 0.23951707, 0.16709936,
       0.08042936, 0.49766486, 0.10133043, 0.21554823, 0.08800584,
       0.26764588, 0.15881901, 0.29369185, 0.21401465, 0.25527346,
       0.2521542 , 0.46994299, 0.14737653, 0.35951835, 0.38511639,
       0.26175056, 0.29687734, 0.23726502, 0.53841882, 0.15319437,
       0.32484026, 0.19022123, 0.25662826, 0.26340184, 0.21650188,
       0.51672287, 0.19941482, 0.40726568, 0.3121707 , 0.08702929,
       0.43688382, 0.07422315, 0.16707696, 0.53837889, 0.5479204 ,
       0.13127392, 0.35912455, 0.1575291 , 0.18346017, 0.50514541,
       0.25892523, 0.29345218, 0.40463074, 0.27394622, 0.36641449,
       0.18225345, 0.40435569, 0.17308299, 0.36784782, 0.27907629,
       0.22395246, 0.45965911, 0.4025057 , 0.39947098])